// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xuwbrzbzctutmmoiszad.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh1d2JyemJ6Y3R1dG1tb2lzemFkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3NTk3MTIsImV4cCI6MjA2OTMzNTcxMn0.suGOtHxPqCuRCWZIITi-SEhaisjOtYwJmdSY6sMrmLM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});